version: "3"
services:
  service1:
    container_name: ${CONTAINER_PREFIX}-service1
    networks:
      - mesh
    image: service1
    env_file:
      - ./.env
    ports:
      - 8081:8080
    environment:
      DB_URL: ${CONTAINER_PREFIX}-db:${DB_PORT_CONTAINER}/${DB_NAME}
  service2:
    container_name: ${CONTAINER_PREFIX}-service2
    networks:
      - mesh
    image: service2
    env_file:
      - ./.env
    ports:
      - 8082:8080
    environment:
      DB_URL: ${CONTAINER_PREFIX}-db:${DB_PORT_CONTAINER}/${DB_NAME}
  db:
    container_name: ${CONTAINER_PREFIX}-db
    networks:
      - mesh
    image: postgres:16.4
    ports:
      - ${DB_PORT_HOST}:${DB_PORT_CONTAINER}
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - ./docker/db/postgres:/var/lib/postgres
networks:
  mesh:
    driver: bridge