spring:
  application:
    name: service2
  profiles:
    native:
      flyway:
        enabled: false
  datasource:
    url: jdbc:postgresql://${DB_URL}?currentSchema=service2
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate.default_schema: service2
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    schemas: service2
    default-schema: service2
